# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'static/ui/Account.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_Account(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 800)
        Dialog.setStyleSheet("background-color: #fadccb;")
        self.topMenu = QtWidgets.QFrame(Dialog)
        self.topMenu.setGeometry(QtCore.QRect(110, 0, 991, 71))
        self.topMenu.setStyleSheet("padding: 0  50 0 0px;")
        self.topMenu.setObjectName("topMenu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topMenu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categoryText = QtWidgets.QLabel(self.topMenu)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.categoryText.setFont(font)
        self.categoryText.setStyleSheet("color: #281401;\n"
                                        "padding-left: 50px;\n"
                                        "")
        self.categoryText.setObjectName("categoryText")
        self.horizontalLayout.addWidget(self.categoryText)
        self.calendarBtn = QtWidgets.QPushButton(Dialog)
        self.calendarBtn.setGeometry(QtCore.QRect(0, 220, 109, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarBtn.sizePolicy().hasHeightForWidth())
        self.calendarBtn.setSizePolicy(sizePolicy)
        self.calendarBtn.setMaximumSize(QtCore.QSize(16777215, 110))
        self.calendarBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.calendarBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.calendarBtn.setAutoFillBackground(False)
        self.calendarBtn.setStyleSheet("QPushButton{padding: 12px 0px 16px 0px;\n"
                                       "  justify-content: center;\n"
                                       "  align-items: center;\n"
                                       "  gap: 4px;}\n"
                                       "QPushButton:hover {\n"
                                       "background: #FFF1ED;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed{\n"
                                       "background: #FFEAE5;\n"
                                       "}")
        self.calendarBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/ui\\../img/calendar_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendarBtn.setIcon(icon)
        self.calendarBtn.setIconSize(QtCore.QSize(85, 100))
        self.calendarBtn.setAutoDefault(False)
        self.calendarBtn.setDefault(False)
        self.calendarBtn.setFlat(True)
        self.calendarBtn.setObjectName("calendarBtn")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(109, 79, 991, 701))
        self.frame.setStyleSheet("background-color: white;\n"
                                 "    border-top-left-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.imageLabel = QtWidgets.QLabel(self.frame)
        self.imageLabel.setGeometry(QtCore.QRect(100, 50, 250, 250))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.nameText = QtWidgets.QLabel(self.frame)
        self.nameText.setGeometry(QtCore.QRect(420, 60, 151, 49))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.nameText.setFont(font)
        self.nameText.setStyleSheet("color: #281401;\n"
                                    "")
        self.nameText.setObjectName("nameText")
        self.userName = QtWidgets.QLineEdit(self.frame)
        self.userName.setGeometry(QtCore.QRect(660, 60, 251, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userName.sizePolicy().hasHeightForWidth())
        self.userName.setSizePolicy(sizePolicy)
        self.userName.setMinimumSize(QtCore.QSize(0, 50))
        self.userName.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.userName.setFont(font)
        self.userName.setStyleSheet("QLineEdit{background-color: rgb(255, 255, 255);\n"
                                    "  border-width: 1px;\n"
                                    "  border-style: solid;\n"
                                    "  border-color: #79747e;\n"
                                    "  border-radius: 4px;\n"
                                    "  gap: 10px;\n"
                                    "padding-left: 10px;}\n"
                                    "QLineEdit:focus{\n"
                                    "border-color: #E77D66;\n"
                                    "border-width: 2px;\n"
                                    "}")
        self.userName.setText("")
        self.userName.setMaxLength(150)
        self.userName.setCursorPosition(0)
        self.userName.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.userName.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.userName.setObjectName("userName")
        self.birthdateText = QtWidgets.QLabel(self.frame)
        self.birthdateText.setGeometry(QtCore.QRect(420, 140, 221, 49))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.birthdateText.setFont(font)
        self.birthdateText.setStyleSheet("color: #281401;\n"
                                         "")
        self.birthdateText.setObjectName("birthdateText")
        self.userBirthdate = QtWidgets.QDateEdit(self.frame)
        self.userBirthdate.setGeometry(QtCore.QRect(660, 140, 251, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userBirthdate.sizePolicy().hasHeightForWidth())
        self.userBirthdate.setSizePolicy(sizePolicy)
        self.userBirthdate.setMinimumSize(QtCore.QSize(0, 50))
        self.userBirthdate.setMaximumSize(QtCore.QSize(16777215, 50))
        self.userBirthdate.setStyleSheet("QDateEdit{background-color: rgb(255, 255, 255);\n"
                                         "  border-width: 1px;\n"
                                         "  border-style: solid;\n"
                                         "  border-color: #79747e;\n"
                                         "  border-radius: 4px;\n"
                                         "  gap: 10px;\n"
                                         "padding-left: 10px;}\n"
                                         "QDateEdit:focus{\n"
                                         "border-color: #E77D66;\n"
                                         "border-width: 2px;\n"
                                         "}")
        self.userBirthdate.setFrame(True)
        self.userBirthdate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.userBirthdate.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.userBirthdate.setObjectName("userBirthdate")
        self.previousButton = QtWidgets.QPushButton(self.frame)
        self.previousButton.setGeometry(QtCore.QRect(140, 310, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousButton.sizePolicy().hasHeightForWidth())
        self.previousButton.setSizePolicy(sizePolicy)
        self.previousButton.setMaximumSize(QtCore.QSize(16777215, 110))
        self.previousButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.previousButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.previousButton.setAutoFillBackground(False)
        self.previousButton.setStyleSheet("QPushButton{\n"
                                          "  justify-content: center;\n"
                                          "  align-items: center;\n"
                                          "  gap: 4px;\n"
                                          "border-radius: 10px;}\n"
                                          "QPushButton:hover {\n"
                                          "background: #FFF1ED;\n"
                                          "\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:pressed{\n"
                                          "background: #FFEAE5;\n"
                                          "}")
        self.previousButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/ui\\../img/icon-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon1)
        self.previousButton.setIconSize(QtCore.QSize(85, 100))
        self.previousButton.setAutoDefault(False)
        self.previousButton.setDefault(False)
        self.previousButton.setFlat(True)
        self.previousButton.setObjectName("previousButton")
        self.nextButton = QtWidgets.QPushButton(self.frame)
        self.nextButton.setGeometry(QtCore.QRect(240, 310, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setMaximumSize(QtCore.QSize(16777215, 110))
        self.nextButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.nextButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.nextButton.setAutoFillBackground(False)
        self.nextButton.setStyleSheet("QPushButton{\n"
                                      "  justify-content: center;\n"
                                      "  align-items: center;\n"
                                      "  gap: 4px;\n"
                                      "border-radius: 10px;}\n"
                                      "QPushButton:hover {\n"
                                      "background: #FFF1ED;\n"
                                      "\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "background: #FFEAE5;\n"
                                      "}")
        self.nextButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/ui\\../img/icon-button-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon2)
        self.nextButton.setIconSize(QtCore.QSize(85, 100))
        self.nextButton.setAutoDefault(False)
        self.nextButton.setDefault(False)
        self.nextButton.setFlat(True)
        self.nextButton.setObjectName("nextButton")
        self.saveUserDataBtn = QtWidgets.QPushButton(self.frame)
        self.saveUserDataBtn.setGeometry(QtCore.QRect(420, 250, 176, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveUserDataBtn.sizePolicy().hasHeightForWidth())
        self.saveUserDataBtn.setSizePolicy(sizePolicy)
        self.saveUserDataBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.saveUserDataBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.saveUserDataBtn.setFont(font)
        self.saveUserDataBtn.setStyleSheet("QPushButton{position: absolute;\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "  background-color: #e77d66;\n"
                                           "  border-radius: 20%;\n"
                                           "  gap: 8px;\n"
                                           "}")
        self.saveUserDataBtn.setObjectName("saveUserDataBtn")
        self.accountBtn = QtWidgets.QPushButton(Dialog)
        self.accountBtn.setGeometry(QtCore.QRect(0, 340, 109, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountBtn.sizePolicy().hasHeightForWidth())
        self.accountBtn.setSizePolicy(sizePolicy)
        self.accountBtn.setMaximumSize(QtCore.QSize(16777215, 110))
        self.accountBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.accountBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.accountBtn.setAutoFillBackground(False)
        self.accountBtn.setStyleSheet("QPushButton{padding: 12px 0px 16px 0px;\n"
                                      "  justify-content: center;\n"
                                      "  align-items: center;\n"
                                      "  gap: 4px;}\n"
                                      "QPushButton:hover {\n"
                                      "background: #FFF1ED;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "background: #FFEAE5;\n"
                                      "}")
        self.accountBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/ui\\../img/account_selected_btn.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.accountBtn.setIcon(icon3)
        self.accountBtn.setIconSize(QtCore.QSize(85, 100))
        self.accountBtn.setAutoDefault(False)
        self.accountBtn.setDefault(False)
        self.accountBtn.setFlat(True)
        self.accountBtn.setObjectName("accountBtn")
        self.eventsBtn = QtWidgets.QPushButton(Dialog)
        self.eventsBtn.setGeometry(QtCore.QRect(0, 110, 109, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventsBtn.sizePolicy().hasHeightForWidth())
        self.eventsBtn.setSizePolicy(sizePolicy)
        self.eventsBtn.setMaximumSize(QtCore.QSize(16777215, 110))
        self.eventsBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.eventsBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.eventsBtn.setAutoFillBackground(False)
        self.eventsBtn.setStyleSheet("QPushButton{padding: 12px 0px 16px 0px;\n"
                                     "  justify-content: center;\n"
                                     "  align-items: center;\n"
                                     "  gap: 4px;}\n"
                                     "QPushButton:hover {\n"
                                     "background: #FFFFFF;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed{\n"
                                     "background: #FFEAE5;\n"
                                     "}\n"
                                     "")
        self.eventsBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/ui\\../img/events_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eventsBtn.setIcon(icon4)
        self.eventsBtn.setIconSize(QtCore.QSize(85, 100))
        self.eventsBtn.setCheckable(False)
        self.eventsBtn.setAutoDefault(False)
        self.eventsBtn.setDefault(False)
        self.eventsBtn.setFlat(True)
        self.eventsBtn.setObjectName("eventsBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MyEvents"))
        self.categoryText.setText(_translate("Dialog", "Профиль"))
        self.nameText.setText(_translate("Dialog", "Имя:"))
        self.userName.setPlaceholderText(_translate("Dialog", "Ваше имя"))
        self.birthdateText.setText(_translate("Dialog", "День рождения:"))
        self.userBirthdate.setDisplayFormat(_translate("Dialog", "dd.MM"))
        self.saveUserDataBtn.setText(_translate("Dialog", "Сохранить"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UI_Account()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
